### ISSUE TITLE
Issue with the updated seisflows installation

### ISSUE THREAD

**Issue by mishuyetsam** [adjtomo/seisflows#166]
I have been trying to freshly install seisflows and pyatoa under an environment called 'adjtomo'. However, I noticed that the seisflows package does not require the requirements.txt file anymore. On following the instructions (https://seisflows.readthedocs.io/en/latest/), it seems to create a new environment called 'seisflows'. 
How do I fix this?
![Selection_076](https://user-images.githubusercontent.com/115526918/227868276-7452e869-c94d-475f-adef-8de30820ece8.png)
![Selection_075](https://user-images.githubusercontent.com/115526918/227868285-cd9bc5aa-3b9b-4f05-9ba3-7b20f8c471eb.png)
![Selection_074](https://user-images.githubusercontent.com/115526918/227868288-1fc25741-b22e-4f36-8e47-a2e24ac4a8bf.png)

**Comment by bch0w** [comment]
Hi @mishuyetsam, sorry you're having trouble with installation. Yes, since the changes introduced in #149, we did away with the `requirements.txt` and `setup.py` files in favor of a new `pyproject.toml` file. These accomplish the same task of allowing SeisFlows to be installed as a package.

Thank you for pointing this out. After trying this out myself I realize the alternative instructions are incorrect and will only allow creating an environment called `seisflows` as you have experienced. You will need to add a `-n/--name` flag to specifically name the Conda environment you want to install to. That is:

```bash
conda create -n adjtomo
# git clone and cd to seisflows
conda env update -f environment.yml -n adjtomo
conda activate adjtomo
```

I just tried this out on my machine and was successfully able to install SeisFlows into my `adjtomo` environment

```bash
(adjtomo) [bchow@blackbox seisflows]$ conda env update -f environment.yml -n adjtomo
...
# To activate this environment, use
#
#     $ conda activate adjtomo
#
# To deactivate an active environment, use
#
#     $ conda deactivate
(adjtomo) [bchow@blackbox seisflows]$ seisflows
usage: seisflows [-h] [-w [WORKDIR]] [-p [PARAMETER_FILE]]
                 {setup,configure,swap,submit,resume,restart,clean,par,sempar,check,init,plot2d,plotst,print,reset,debug,examples}
```

Please let me know if that works for you. If so then I will update the documentation page with the corrected installation procedure.

**Comment by mishuyetsam** [comment]
Thank you for the concise explanation. I followed it and it's finally set up and running!

**Comment by bch0w** [comment]
Closing as complete! Please re-open if this issue still persists for you.
