### ISSUE TITLE
problems related to PBS clusters

### ISSUE THREAD

**Issue by rmodrak** [adjtomo/seisflows#18]
One issue: PBS Pro and Toque are in many ways different and may require separate modules in seisflows/system.

**Comment by rmodrak** [comment]
On Wed, Feb 24, 2016 at 1:37 PM, Gian Matharu <gian@ualberta.ca> wrote:
    Hey Ryan, 

     I was wondering if you'd noticed any lag between seisflows executing commands on clusters. I seem to have noticed that there are lags between ending one call and proceeding to another despite being seemingly complete with the prior task. 


No, I don't believe we've had that problem.  Perhaps some sort of 'epilogue'?  http://docs.adaptivecomputing.com/torque/3-0-5/a.gprologueepilogue.php  Or perhaps just unreliable behavior of PBS.

**Comment by rmodrak** [comment]
Update:  By replacing pbs environment variables with mpi directives, gian's system.mpi class removes the need to distinguish between pbs pro and torque in some cases; pbs_sm should work for both variants, I believe.  To my knowledge, pbs_lg has been tested on pbs pro clusters but still needs testing on pbs torque clusters (while it may work on the latter with small modifications, it is not likely to work right out of the box).

**Comment by gianmatharu** [comment]
I ran into another topic that may warrant some consideration. For the PBS cluster I'm currently using, certain software needs to be loaded prior to running codes e.g. "module load intel" will load intel compilers etc. Admittedly, I'm not sure if this is standard for PBS/clusters in general but would adding the option to specify such directives from within the seisflows system.submit be beneficial? 

There are easy alternatives (using bash profiles or in some cases one could use a submission script to submit sfrun), so it's not a pressing issue and may not be necessary.

**Comment by rmodrak** [comment]
For controlling user environment, I think the module utility is standard
for all types of clusters, not just PBS.  I can't think of a cluster I've
used that hasn't had it.  However, the list of available modules itself
(``module avail``) is highly system dependent, so trying to script ``module
load ...`` may not be a good approach.

A better approach I think would be to include environment assertions in
``check`` methods.  For example, if ``mpi4py`` is required but not on the
PYTHONPATH, an environment exception should be returned.

**Comment by dkzhangchao** [comment]
Hi Ryan, 
Sorry for bothering you again, Actually I also meet with bugs when using system='pbs_sm', i am not sure if it's cause by the mpi4py.

when i use system='pbs_sm', mpi4py can be loaded (import mpi4py),  my ntask=8
It met the bug when generate the observe data
![screenshot from 2016-09-23 11 10 39](https://cloud.githubusercontent.com/assets/8068058/18790858/74f3109a-817e-11e6-857c-59aa89351a24.png)

it's wired, because i can get through  'bin/xmeshfem2D'  but it failed 'bin/xspecfem2D'
after 'bin/xmeshfem2D' , it generate the corresponding Database, which is nomal
![screenshot from 2016-09-23 11 15 35](https://cloud.githubusercontent.com/assets/8068058/18791093/5c26c736-817f-11e6-9bf9-be6be003d5d8.png)
However, when run the 'bin/xspecfem2D', it meets bug
[gpc-f106n012-ib0:30348] [[7631,1],2] routed:binomial: Connection to lifeline [[7631,0],0] lost
[gpc-f106n012-ib0:30353] [[7631,1],7] routed:binomial: Connection to lifeline [[7631,0],0] lost
[gpc-f106n012-ib0:30349] [[7631,1],3] routed:binomial: Connection to lifeline [[7631,0],0] lost
[gpc-f106n012-ib0:30351] [[7631,1],4] routed:binomial: Connection to lifeline [[7631,0],0] lost
[gpc-f106n012-ib0:30350] [[7631,1],1] routed:binomial: Connection to lifeline [[7631,0],0] lost
[gpc-f106n012-ib0:30352] [[7631,1],6] routed:binomial: Connection to lifeline [[7631,0],0] lost
[gpc-f106n012-ib0:30355] [[7631,1],5] routed:binomial: Connection to lifeline [[7631,0],0] lost
[gpc-f106n012-ib0:30355] [[7631,1],0] routed:binomial: Connection to lifeline [[7631,0],0] lost
Do you know what this means? Actually, in each profile  scratch/solver/0000000*
if i print the './bin/xspecfem2d', all of them can forward, can you give me some suggestion
Thanks

**Comment by rmodrak** [comment]
It seems like ``pbs_sm`` is not working on your cluster.  Similar to the problem described [here](http://stackoverflow.com/questions/21911354/mpi4py-routedbinomial-connection-to-lifeline-lost
), mpi4py seems to fail when encountering Python subprocess calls.  Strangely, on other PBS clusters, this is not always an issue.

As a workaround, try using ``pbs_md`` instead, which uses pbsdsh under the hood rather than mpi4py.

In case others run into this problem, I'll go ahead edit your post for clarity if that's alright.

**Comment by rmodrak** [comment]
Sorry, I meant to say try using ``pbs_torque_sm`` instead.

**Comment by gianmatharu** [comment]
The MPI (mpi4py) system class may not be an ideal solution to task parallelism on clusters. It is an approach that aims to provide flexibility between cluster resource managers. While I haven't encountered the particular issue above, I have encountered issues with the class in other forms. As Ryan has suggested, it is probably best to try and utilize utilities provided by the resource manager (e.g. pbsdsh).

**Comment by rmodrak** [comment]
Thanks everyone for the useful comments.  I've opened a new issue #40 for discussing shot parallelism problems of the kind Chao is experiencing.  In this new issue, I've posted some previous emails between Gian and myself that seem relevant to the problem at hand.

**Comment by dkzhangchao** [comment]
Hi Ryan, gianmatharu  

1) on our pbs cluster, firstly i load these module automatically when i log in 
module load intel/14.0.1
module load gcc/5.2.0
module load openmpi/1.4.4-intel-v12.1
module load python/2.7.5
Actually, if i print the command: python -c "import mpi4py", it can work. When the coding is running, there is also no error information about mpi4py, so it should be loaded well

2) Anyway, i also tried the system='pbs_torque_sm', there is a bug about import

Traceback (most recent call last):
File "/scratch/l/liuqy/zhang18/Research/packages/seisflows/seisflows/system/wrappers/run_pbsdsh", line 15, in 
from seisflows.tools.code import loadjson, loadobj
ImportError : from seisflows.tools.code import loadjson, loadobj

Actually, this problem also occur when i used system='pbs_sm', if i just load modules( module intel/14.0.1,gcc/5.2.0,1.4.4-intel-v12.1, python/2.7.5) at the submit node, it will meet the problem like above issue; If module are loaded automatically when i log in every time, it will not
meet this problem. So i use my .bashrc to load these module automatically, but even though, this problem occur again for the system='pbs_torque_sm'

**Comment by dkzhangchao** [comment]
when i log in every time, these module will be load. I tried 
python -c "from seisflows.tools.code import loadjson, loadobj", it can work
<img width="896" alt="qq20160923-0 2x" src="https://cloud.githubusercontent.com/assets/8068058/18801236/8c1e86ba-81af-11e6-8d2d-adf3e9f82289.png">

**Comment by dkzhangchao** [comment]
Hi Ryan and Gian,

I have tried system='pbsdsh', i also meet the same problems when it execute the 

        system.run('solver', 'setup', 
                   hosts='all')
<img width="720" alt="11" src="https://cloud.githubusercontent.com/assets/8068058/18825181/0f90753a-8395-11e6-95c5-0ee7f81da1ab.png">

Actually, i generated the observe data after this, it means that the pbsdsh can be evoked here.
However, it seems that it's stuck in the  system.run ( subprocess.call(pbsdsh)  ). The bug is showed below:
![22](https://cloud.githubusercontent.com/assets/8068058/18825372/0fc398c4-8396-11e6-8328-36b0511bf6a0.png) 

Can you give me advice? BTW, i can get the forward result (obs data)  after system.run

**Comment by gianmatharu** [comment]
It does appear to be hanging, but it is not the issue I saw in issue #40
(where mpi4py was used). It seems to be due to pbsdsh hanging, which I have
encountered. The issue is inconsistent for me, It can occur on one attempt
and not the subsequent attempt. I don't observe it that frequently any
more.

What workflow are you attempting to run? I'd suggest checking any instances
of system.run (within the worfklow) to check that all the calls to pbsdsh
aren't problematic.

**Comment by dkzhangchao** [comment]
I do the inversion in workflow.   This is the first time to invoke system.run ( that is, forwarding to  get the observe data) , i am confused that if the system.run has some problem, why it also generate the data after execute the code

 system.run('solver', 'setup',
                hosts='all')
BTW, do you think my command of system.run is correct?
<img width="720" alt="11" src="https://cloud.githubusercontent.com/assets/8068058/18841434/b8ed5f7c-83df-11e6-8e7c-9aca50f095eb.png">

**Comment by rmodrak** [comment]
Perhaps using pbsdsh to invoke a simple "hello world" script might be
useful as a  debugging step.  The integration test located in
seisflows/tests/test_system could be employed for this purpose.

That said, my understanding from speaking to our local cluster
administrator is that the  pbsdsh utility itself can be unreliable.  This
may well be the explanation for what you are seeing, but it may be worth
troubleshooting a bit to make sure there's not some alternate explanation.

**Comment by rmodrak** [comment]
If pbsdsh is in fact the problem, a workaround might be to create a your
own dsh script by calling ssh within a for loop.  You would need to (1)
manually specify the compute nodes to run on (2) use the SendEnv option or
something similar to assign each ssh process a unique indentifier and (3)
wait until all the ssh processes complete before moving.  A disadvantage of
this approach might be that the child ssh processes might continue running
in the event the parent process fails.

**Comment by rmodrak** [comment]
Yet another workaround would be to write an entirely new PBS system class
based the following package:

https://radicalpilot.readthedocs.io/en/latest/

Through an NSF grant, we are currently collaborating with the developers of
the radical pilot package, so such an interface might eventually be added
to seisflows but not for a while yet.  If you get something to work in the
meantime please feel free to submit a pull request.

**Comment by rmodrak** [comment]
To reflect the expanded scope of the discussion, I'll go ahead and change the issue title to something more general.

Also, it's worth noting that none of the problems mentioned above have been encountered on SLURM clusters.  So if the possibility ever arises to switch to SLURM I'd highly recommend it...

**Comment by dkzhangchao** [comment]
Hi Rran,
Yep, i agree with you. To be honest, there are more issues for pbs system than slurm. The staff of my cluster tells me that it seems there is a problem for pbsdsh, i write a scrip which emulates the behavior of pbsdsh. Does it accord with your suggestion?

![111](https://cloud.githubusercontent.com/assets/8068058/18860115/516871ac-8448-11e6-9103-a477667e89b0.png)
Then it can run successfully, but compared with pbsdsh, it's running much slower.

**Comment by rmodrak** [comment]
This is definitely in the right direction.  You need to wait afterward until all processes finish.  If you were implementing it in bash, it might be something like you have written.  However, since you would be overloading the 'run' method from the pbs system class, actually it needs to be implemented in python.  Come to think of it, in python it would be probably be better to use parminko than a subprocess call to ssh (see following link).

http://stackoverflow.com/questions/3586106/perform-commands-over-ssh-with-python
